

/*
 Basic ESP8266 MQTT example
 This sketch demonstrates the capabilities of the pubsub library in combination
 with the ESP8266 board/library.
 It connects to an MQTT server then:
  - publishes "hello world" to the topic "outTopic" every two seconds
  - subscribes to the topic "inTopic", printing out any messages
    it receives. NB - it assumes the received payloads are strings not binary
  - If the first character of the topic "inTopic" is an 1, switch ON the ESP Led,
    else switch it off
 It will reconnect to the server if the connection is lost using a blocking
 reconnect function. See the 'mqtt_reconnect_nonblocking' example for how to
 achieve the same result without blocking the main loop.
 To install the ESP8266 board, (using Arduino 1.6.4+):
  - Add the following 3rd party board manager under "File -> Preferences -> Additional Boards Manager URLs":
       http://arduino.esp8266.com/stable/package_esp8266com_index.json
  - Open the "Tools -> Board -> Board Manager" and click install for the ESP8266"
  - Select your ESP8266 in "Tools -> Board"
*/
#include <math.h>

#include <ArduinoJson.h>
#include <ESP8266WiFi.h>
#include <WiFiManager.h>
#include <PubSubClient.h>
#include <OneButton.h>
#include <FS.h>
#include "TemperatureValueTable.h"

#define DEVICE_NAME "light_yugang8"

#define LIGHT_STATE_CHANNEL "homedevice/light/yugang8/light/status"
#define LIGHT_COMMAND_CHANNEL "homedevice/light/yugang8/light/switch"
#define LIGHT_BRIGHT_STATE_CHANNEL "homedevice/light/yugang8/lightbrightness/status"
#define LIGHT_BRIGHT_COMMAND_CHANNEL "homedevice/light/yugang8/lightbrightness/set"

#define PUMB_STATE_CHANNEL "homedevice/light/yugang8/pumb/status"
#define PUMB_COMMAND_CHANNEL "homedevice/light/yugang8/pumb/switch"
#define PUMB_BRIGHT_STATE_CHANNEL "homedevice/light/yugang8/pumbbrightness/status"
#define PUMB_BRIGHT_COMMAND_CHANNEL "homedevice/light/yugang8/pumbbrightness/set"
      
#define HEATER_STATE_CHANNEL "homedevice/switch/yugang8/heater/status"
#define HEATER_COMMAND_CHANNEL "homedevice/switch/yugang8/heater/switch"

#define DISCOVER_CHANNEL "homedevice/light/yugang8/config"
#define STATE_CHANNEL "homedevice/light/yugang8/status"

#define TEMP_CHANNEL "homedevice/sensor/yugang8/temperature/status"

#define TARGET_COMMAND_SET_LOW_CHANNEL "homedevice/yugang8/light/setLow"
#define TARGET_COMMAND_SET_HIGH_CHANNEL "homedevice/yugang8/light/setHigh"

#define DEVICE_COMMAND "homedevice/yugang8/command"
#define DEVICE_STATUS "homedevice/yugang8/status"

//#define CLIENT_ID "ESP8266Client-522b"
//#define CLIENT_PASSWORD "autogenerated_token_522b_7fb50d48-342a-11ed-a261-0242ac120002"
#define MQTT_BROKER_HOST "192.168.50.109"
//#define MQTT_BROKER_HOST "onwebbe.gicp.net"
#define MQTT_BROKER_PORT 9013

// #define WIFI_NAME "HUAWEI—7539"
#define WIFI_NAME "pankey_asus"
#define WIFI_PASSWORD "1234554321"
#define LIGHT_PIN 13
#define HEATER_PIN 12
#define PUMB_PIN 14
#define RESET_NETWORK_BUTTON_PIN 16
#define SWITCH_BUTTON_PIN 5

#define CLIENT_ID "HomeAssistantSmart_yugang_8"
#define  CLIENT_PASSWORD "smartyugang_8"
// Update these with values suitable for your network.
const int TEMPERATURE_PIN = A0;
const char* ssid = WIFI_NAME;
const char* password = WIFI_PASSWORD;
String mqtt_server("192.168.50.109");
WiFiClient espClient;
PubSubClient client(espClient);
unsigned long lastHeartBeat = 0;
unsigned long lastStatusUpate = 0;
#define MSG_BUFFER_SIZE  (50)
char msg[MSG_BUFFER_SIZE];
int value = 0;
boolean shouldSaveConfig = false;

int tempHigh = 30;
int tempLow = 26;
int brightnessValue = 100;
int pumbbrightnessValue = 140;
WiFiManager wm;
OneButton resetNetworkButton(RESET_NETWORK_BUTTON_PIN, true);
OneButton switchButton(SWITCH_BUTTON_PIN, true);
boolean isOn = false;
boolean isPumbOn = false;
boolean isHeaterOn = false;
      

unsigned int Rs = 150000;//R1取值为150k
double Vcc = 3.3;
double temperatureValue[242];
double rValue[242];

String readFile(const char * path) {
  Serial.printf("Reading file: %s\n", path);

  File file = SPIFFS.open(path, "r");
  if (!file) {
    Serial.println("Failed to open file for reading");
    return "";
  }

  Serial.print("Read from file: ");
  Serial.print(file.size());
  String result;
  if (SPIFFS.exists(path)) {
    for(int i = 0; i < file.size(); i++) {
      int intData = file.read();
      Serial.write(intData);
      result = result + (char)intData;
    }
  }
  file.close();
  return result;
}

void writeFile(const char * path, const char * message) {
  Serial.printf("Writing file: %s\nand file content: %s", path, message);

  File file = SPIFFS.open(path, "w");
  if (!file) {
    Serial.println("Failed to open file for writing");
    return;
  }
  if (file.print(message)) {
    Serial.println("File written");
  } else {
    Serial.println("Write failed");
  }
  delay(2000); // Make sure the CREATE and LASTWRITE times are different
  file.close();
  SPIFFS.end();
}

void Split(String zifuchuan,String fengefu,String result[]) {
  int weizhi; //找查的位置
  String temps;//临时字符串
  int i=0;
  do {
    weizhi = zifuchuan.indexOf(fengefu);//找到位置
    if(weizhi != -1) { //如果位置不为空
        temps=zifuchuan.substring(0,weizhi);//打印取第一个字符
        zifuchuan = zifuchuan.substring(weizhi+fengefu.length(), zifuchuan.length());
        //分隔后只取后面一段内容 以方便后面找查
    }
    else {  //上面实在找不到了就把最后的 一个分割值赋值出来以免遗漏
       if(zifuchuan.length() > 0)
        temps=zifuchuan;
    }
    result[i++]=temps;
    //Serial.println(result[i-1]);//在这里执行分割出来的字符下面不然又清空了
    temps="";
 }
 while(weizhi >= 0);
}

void resetNetworkSettingsWhenFailed() {
  Serial.println("reset network settings");
  delay(1000);
  wm.resetSettings();
  delay(5000);
  Serial.println("restart");
  ESP.restart();
}
void saveConfigCallback() {
  Serial.println("Should save config");
  shouldSaveConfig = true;
}
void setup_wifi() {
  Serial.println("Start setup WIFI");
  delay(10);
  // We start by connecting to a WiFi network
  //WiFiManager, Local intialization. Once its business is done, there is no need to keep it around
//  WiFiManager wm;
  // reset settings - wipe stored credentials for testing
  // these are stored by the esp library
  // wm.resetSettings();

  wm.setSaveConfigCallback(saveConfigCallback);

  // Automatically connect using saved credentials,
  // if connection fails, it starts an access point with the specified name ( "AutoConnectAP"),
  // if empty will auto generate SSID, if password is blank it will be anonymous AP (wm.autoConnect())
  // then goes into a blocking loop awaiting configuration and will return success result
  char clientid[] = CLIENT_ID;
  char clientpwd[] = CLIENT_PASSWORD;
  mqtt_server = MQTT_BROKER_HOST;
  int clientIPLength = mqtt_server.length() + 1;
  char clientIP[clientIPLength];
  mqtt_server.toCharArray(clientIP, clientIPLength);
  WiFiManagerParameter custom_client_id("clientid", "Client Id", clientid, 50);
  WiFiManagerParameter custom_client_pwd("clientpwd", "Client Pass", CLIENT_PASSWORD, 100);
  WiFiManagerParameter custom_client_ip("clientip", "Client IP", clientIP, 100);
  wm.addParameter(&custom_client_id);
  wm.addParameter(&custom_client_pwd);
  wm.addParameter(&custom_client_ip);
  bool res;
  // res = wm.autoConnect(); // auto generated AP name from chipid
  // res = wm.autoConnect("AutoConnectAP"); // anonymous ap
  String strDeviceName = DEVICE_NAME;
  String wifiName = "SmartYugang-" + strDeviceName;
  Serial.print("Creating wifi");
  Serial.print(wifiName);
  Serial.println();
  res = wm.autoConnect(wifiName.c_str(), ""); // password protected ap

  if(!res) {
      Serial.println("Failed to connect");
      delay(300000);
      ESP.restart();
  }
  Serial.println("connected...yeey :)");
  Serial.println(custom_client_id.getValue());
  Serial.println(custom_client_pwd.getValue());
  Serial.println(custom_client_ip.getValue());
  Serial.println("--------get wifi ssid--------");
  Serial.println(wm.getWiFiPass());
  Serial.println(ssid);
  String client_id = custom_client_id.getValue();
  String client_password = custom_client_pwd.getValue();
  String client_ip = custom_client_ip.getValue();
  Serial.print("CLIENT_ID: ");
  Serial.print(client_id);
  Serial.print(":::::");
  Serial.println();
  Serial.print("CLIENT_PASSWORD: ");
  Serial.print(client_password);
  Serial.print(":::::");
  Serial.print("CLIENT_IP: ");
  Serial.print(client_ip);
  Serial.print(":::::");
  Serial.println();
  mqtt_server = client_ip;
}

void callback(char* topic, byte* payload, unsigned int length) {
  
  String topicString(topic);
  String setLowString(TARGET_COMMAND_SET_LOW_CHANNEL);
  String setHighString(TARGET_COMMAND_SET_HIGH_CHANNEL);
  char payloadChar[length];
  for(int i = 0; i < length; i++) {
    payloadChar[i] = (char) payload[i];
  }
  String payloadString(payloadChar);
  Serial.print("Payload length:");
  Serial.println(length);
  Serial.print("Payload data:");
  Serial.println(payloadChar);
  Serial.print("Message arrived [");
  Serial.print(topicString);
  Serial.print("] [");
  Serial.print(payloadString);
  Serial.println("]");
  if (topicString.equals(setLowString)) {
    tempLow = payloadString.toInt();
  } else if (topicString.equals(setHighString)) {
    tempHigh = payloadString.toInt();
  } else if (topicString.equals(LIGHT_COMMAND_CHANNEL)) {
    Serial.println("Light switch received");
    if (payloadString.equals("off")) {
      Serial.println("Switch OFF");
      digitalWrite(LIGHT_PIN, LOW);   // Turn the LED on (Note that LOW is the voltage level
      digitalWrite(BUILTIN_LED, LOW);
      // client.publish(STATE_CHANNEL, "off");
      isOn = false;
    } else {
      Serial.println("Switch ON");
      // digitalWrite(LIGHT_PIN, HIGH);  // Turn the LED off by making the voltage HIGH
      analogWrite(LIGHT_PIN, brightnessValue);
      digitalWrite(BUILTIN_LED, HIGH);
      // client.publish(STATE_CHANNEL, "on");
      isOn = true;
    }
    client.publish(LIGHT_STATE_CHANNEL, isOn?"on":"off");
  } else if (topicString.equals(LIGHT_BRIGHT_COMMAND_CHANNEL)) {
    brightnessValue = payloadString.toInt();
    analogWrite(LIGHT_PIN, brightnessValue);
    
    String brightValueStr(brightnessValue);
    char brightValueStrChar[brightValueStr.length()];
    brightValueStr.toCharArray(brightValueStrChar, brightValueStr.length() + 1);
    client.publish(LIGHT_BRIGHT_STATE_CHANNEL, brightValueStrChar);
    Serial.print("Publish light brightness:[");
    Serial.print(LIGHT_BRIGHT_STATE_CHANNEL);
    Serial.print("] data:[");
    Serial.print(brightValueStrChar);
    Serial.println("]");
  } else if (topicString.equals(PUMB_COMMAND_CHANNEL)) {
    if (payloadString.equals("off")) {
      Serial.println("PUMB OFF");
      digitalWrite(PUMB_PIN, LOW);
      isPumbOn = false;
    } else {
      Serial.println("PUMB ON");
      analogWrite(PUMB_PIN, 255);
      delay(1000);
      analogWrite(PUMB_PIN, pumbbrightnessValue);
      isPumbOn = true;
    }
    client.publish(PUMB_STATE_CHANNEL, isPumbOn?"on":"off");
    String pumbValueStr(pumbbrightnessValue);
    char pumbValueChar[pumbValueStr.length()];
    pumbValueStr.toCharArray(pumbValueChar, pumbValueStr.length() + 1);
    client.publish(PUMB_BRIGHT_STATE_CHANNEL, pumbValueChar);
    
  } else if (topicString.equals(PUMB_BRIGHT_COMMAND_CHANNEL)) {
    pumbbrightnessValue = payloadString.toInt();
    analogWrite(PUMB_PIN, 255);
    delay(1000);
    analogWrite(PUMB_PIN, pumbbrightnessValue);
    Serial.print("PUMB Adjuct:");
    Serial.println(pumbbrightnessValue);

    String pumbValueStr(pumbbrightnessValue);
    char pumbValueChar[pumbValueStr.length()];
    pumbValueStr.toCharArray(pumbValueChar, pumbValueStr.length() + 1);
    client.publish(PUMB_BRIGHT_STATE_CHANNEL, pumbValueChar);
    Serial.print("Publish pumb brightness:[");
    Serial.print(PUMB_BRIGHT_STATE_CHANNEL);
    Serial.print("] data:[");
    Serial.print(pumbValueChar);
    Serial.println("]");
    
  } else if (topicString.equals(HEATER_COMMAND_CHANNEL)) {
    if (payloadString.equals("off")) {
      Serial.println("HEATER OFF");
      digitalWrite(HEATER_PIN, LOW);
      isHeaterOn = false;
    } else {
      Serial.println("HEATER ON");
      digitalWrite(HEATER_PIN, HIGH);
      isHeaterOn = true;
    }
    client.publish(HEATER_STATE_CHANNEL, isHeaterOn?"on":"off");
  } else if (topicString.equals(DEVICE_COMMAND)) {
    if (payloadString.equals("getStatus")) {
      Serial.println("Get Status Command, will update status");
      StaticJsonDocument<96> doc;
      doc["lightswitch"] = isOn?"ON":"OFF";
      doc["lightBright"] = brightnessValue;
      doc["pumbswitch"] = isPumbOn?"ON":"OFF";;
      doc["pumbBright"] = pumbbrightnessValue;
      doc["heaterSwitch"] = isHeaterOn?"ON":"OFF";;
      int tempPin = analogRead(TEMPERATURE_PIN);
      doc["temperature"] = getTemperature(tempPin);;
      String output;
      serializeJson(doc, output);
      Serial.println(output);
      client.publish(DEVICE_STATUS, output.c_str());
    }
  } else {
    Serial.println("Other");
  }
}

void reconnect() {
  // Loop until we're reconnected
  int i = 0;
  digitalWrite(LIGHT_PIN, LOW);
  digitalWrite(PUMB_PIN, LOW);
  digitalWrite(HEATER_PIN, LOW);
  while (!client.connected()) {
    if (i >= 5) {
      // resetNetworkSettingsWhenFailed();
      delay(5000);
      Serial.println("restart");
      ESP.restart();
    }
    Serial.print("Attempting MQTT connection...");
    Serial.print(i);
    // Create a random client ID
    String clientId = CLIENT_ID;
    // clientId += String(random(0xffff), HEX);
    // Attempt to connect
    if (client.connect(clientId.c_str(), "", CLIENT_PASSWORD)) {
      Serial.println("connected");
      // Once connected, publish an announcement...
      const char* publishData = getPublishContent().c_str();
      client.publish(DISCOVER_CHANNEL, publishData);
      // ... and resubscribe  
      client.subscribe(LIGHT_COMMAND_CHANNEL);
      client.subscribe(LIGHT_BRIGHT_COMMAND_CHANNEL);
      client.subscribe(PUMB_COMMAND_CHANNEL);
      client.subscribe(PUMB_BRIGHT_COMMAND_CHANNEL);
      client.subscribe(HEATER_COMMAND_CHANNEL);
      client.subscribe(TARGET_COMMAND_SET_LOW_CHANNEL);
      client.subscribe(TARGET_COMMAND_SET_HIGH_CHANNEL);

      client.subscribe(DEVICE_COMMAND);
      
      digitalWrite(BUILTIN_LED, HIGH);
      
      String strClientId = CLIENT_ID;
      String strPwd = CLIENT_PASSWORD;
      if (!SPIFFS.begin()) {
        Serial.println("LittleFS mount failed");
        return;
      }
      SPIFFS.remove("/network.txt");
      Serial.print("Write to file");
      Serial.print("/network.txt with content:");
      writeFile("/network.txt", (strClientId + "," + strPwd + "," + mqtt_server).c_str());
      SPIFFS.end();

      digitalWrite(HEATER_PIN, isHeaterOn?HIGH:LOW);
      if (isOn) {
        analogWrite(LIGHT_PIN, brightnessValue);
      } else {
        digitalWrite(LIGHT_PIN, LOW);
      }
      
      analogWrite(PUMB_PIN, 255);
      delay(1000);
      analogWrite(PUMB_PIN, pumbbrightnessValue);
    } else {
      Serial.print("failed, rc=");
      Serial.print(client.state());
      Serial.println(" try again in 2 mins");
      // Wait 5 seconds before retrying
      delay(120000);
    }
    i = i + 1;
  }
}
String getPublishContent() {
  String namePart = "{\"name\": \"";
  String uniqueIdPart = "\",\"unique_id\": \"";
  String cmd_TPart = "\",\"cmd_t\": \"";
  String stat_TPart = "\",\"stat_t\": \"";
  String otherPart = "\",\"pl_on\": \"on\",\"pl_off\": \"off\"}";
  String pubContent = namePart  + DEVICE_NAME + uniqueIdPart + DEVICE_NAME + cmd_TPart + LIGHT_COMMAND_CHANNEL + stat_TPart + LIGHT_STATE_CHANNEL + otherPart;
  return pubContent;
}
void heartBeat(PubSubClient *client) {
//  String publishStr = "{\"status\":\"";
//  publishStr.concat(client->state());
//  publishStr.concat("\", \"time\":");
//  publishStr.concat(millis());
//  publishStr.concat("}");
//  Serial.print("Publish heart beat: ");
//  Serial.print(publishStr);
//  Serial.println();
  // client->publish(STATE_CHANNEL, publishStr.c_str());
  // client->publish(STATE_CHANNEL, "online");
  Serial.print("Publish heart beat: ");
  Serial.print(STATE_CHANNEL);
  Serial.print(":");
  Serial.print("online");
  Serial.println();
//  if (isOn) {
//    client->publish(SEND_CHANNEL, "on");
//    client->publish(STATE_CHANNEL, "on");
//  } else {
//    client->publish(SEND_CHANNEL, "off");
//    client->publish(STATE_CHANNEL, "off");
//  }
  
}
void publishStatus(PubSubClient *client) {
  int tempPin = analogRead(TEMPERATURE_PIN);
  Serial.print("Publish temperature: ");
  Serial.print("Low:");
  Serial.println(tempLow);
  Serial.print("High:");
  Serial.println(tempHigh);
  Serial.print("CurrentPin:");
  Serial.println(tempPin);
  Serial.print("Computed Temperature: ");
  double trueTemperature = getTemperature(tempPin);
  Serial.println(trueTemperature);
  String tempString(trueTemperature);
  char tempValueStrChar[tempString.length()];
  tempString.toCharArray(tempValueStrChar, tempString.length() + 1);
  client->publish(TEMP_CHANNEL, tempValueStrChar);
//  
//  if (isHeaterOn) {
//    if (temperature > tempHigh) {
//      digitalWrite(HEATER_PIN, LOW);
//      isHeaterOn = false;
//    }
//  } else {
//    if (temperature < tempLow) {
//      digitalWrite(HEATER_PIN, HIGH);
//      isHeaterOn = true;
//    }
//  }
//  client->publish(HEATER_STATE_CHANNEL, isHeaterOn?"on":"off");
}
void resetNetworkButtonClicked()
{
  SPIFFS.begin();
  SPIFFS.remove("/network.txt");
  SPIFFS.end();
  Serial.println("Network reset Clicked");
  resetNetworkSettingsWhenFailed();
}
int data = 1;
void buttonClicked()
{
  Serial.println("Switch Button Clicked");
  client.publish(LIGHT_COMMAND_CHANNEL, "off");
//  resetNetworkSettingsWhenFailed();
} // doubleClick

void setup() {
  Serial.begin(115200);
  initTemperature();
  
  pinMode(BUILTIN_LED, OUTPUT);
  pinMode(LIGHT_PIN, OUTPUT);     // Initialize the BUILTIN_LED pin as an output
  pinMode(PUMB_PIN, OUTPUT);
  pinMode(HEATER_PIN, OUTPUT);
  pinMode(TEMPERATURE_PIN, INPUT); 
  digitalWrite(LIGHT_PIN, LOW);
  digitalWrite(BUILTIN_LED, LOW);
  digitalWrite(PUMB_PIN, LOW);
  digitalWrite(HEATER_PIN, LOW);
  
  attachInterrupt(digitalPinToInterrupt(RESET_NETWORK_BUTTON_PIN), onNetworkButton, CHANGE);
//  attachInterrupt(digitalPinToInterrupt(SWITCH_BUTTON_PIN), onSwitchButton, CHANGE);

  resetNetworkButton.attachClick(resetNetworkButtonClicked);
  switchButton.attachClick(buttonClicked);
  
  Serial.println("begin start littleFS");
  if (!SPIFFS.begin()) {
    Serial.println("LittleFS mount failed");
    return;
  }

  if (SPIFFS.exists("/network.txt")) {
    Serial.println("network setting file exists");
    String strRaw = readFile("/network.txt");
    String splited[3];
    Split(strRaw, ",", splited);
    String client_id = splited[0];
    String client_password = splited[1];
    String client_ip = splited[2];
    
    String savedPassword = String(WIFI_PASSWORD);
    String savedSSID = wm.getWiFiSSID(true);
    Serial.println(savedSSID);
    Serial.println(wm.getWiFiPass(true));
    
    Serial.print("get setting file");
    Serial.print(client_id);
    Serial.println();
    Serial.print(client_password);
    Serial.println();
    Serial.print(client_ip);
    Serial.println();

    Serial.print(savedSSID);
    Serial.println();
    Serial.print(savedPassword);
    Serial.println();
    mqtt_server = client_ip;
    WiFi.mode(WIFI_STA);
    WiFi.begin(savedSSID, savedPassword);
    int ct = 0;
    for(ct = 0; ct < 500; ct++) {
      if (!WiFi.isConnected()) {
        delay(500);
        Serial.print(".");
      } else {
        Serial.println("connected");
        break;
      }
    }
    // if connect to wifi failed at initial, setup wifi
    if (ct >= 500 ) {
      delay(500);
      ESP.restart();

    }
  } else {
    Serial.println("no file exists");
    setup_wifi();
  }
  SPIFFS.end();
  Serial.println("end start littleFS");

  
  const char *clientIP = mqtt_server.c_str();
  Serial.println("connecting mqtt server");
  Serial.println(clientIP);
  Serial.println("mqtt port");
  Serial.println(MQTT_BROKER_PORT);
  client.setServer(clientIP, MQTT_BROKER_PORT);
  client.setCallback(callback);
  Serial.println("connected wifi");
}
ICACHE_RAM_ATTR void onNetworkButton() {
  Serial.println("onNetworkButton Clicked");
  resetNetworkButton.tick();
}
ICACHE_RAM_ATTR void onSwitchButton() {
  // include all buttons here to be checked
  Serial.println("onSwitchButton Clicked");
  switchButton.tick(); // just call tick() to check the state.
}
void loop() {
  if (!client.connected()) {
    reconnect();
  }
  client.loop();
  resetNetworkButton.tick();
  switchButton.tick();
  
  unsigned long now = millis();
  if ((now - lastHeartBeat) > 10000) {
    lastHeartBeat = now;
    heartBeat(&client);
    publishStatus(&client);
  }
  if ((now - lastStatusUpate) > 2000) {
    lastStatusUpate = now;

  }
}

int AnalogRead() //读取A0采样值，计算20次的平均数
{
  int val = 0;
  for(int i = 0; i < 20; i++) {
    val += analogRead(A0);
    delay(1);
  }

  val = val / 20;
  return val;
}


double thermister(int val) //获取采样平均值利用Steinhart-Hart方程计算温度
{
  double V_NTC = (double)val / 1024;
  double R_NTC = (Rs * V_NTC) / (Vcc - V_NTC);
  R_NTC = log(R_NTC);
  double Temp = 1 / (0.001129148 + (0.000234125 + (0.0000000876741 * R_NTC * R_NTC ))* R_NTC );
  Temp = Temp - 273.15;
  return Temp;

}

void initTemperature() {
  temperatureValue[0]=-20;
  temperatureValue[1]=-19.5;
  temperatureValue[2]=-19;
  temperatureValue[3]=-18.5;
  temperatureValue[4]=-18;
  temperatureValue[5]=-17.5;
  temperatureValue[6]=-17;
  temperatureValue[7]=-16.5;
  temperatureValue[8]=-16;
  temperatureValue[9]=-15.5;
  temperatureValue[10]=-15;
  temperatureValue[11]=-14.5;
  temperatureValue[12]=-14;
  temperatureValue[13]=-13.5;
  temperatureValue[14]=-13;
  temperatureValue[15]=-12.5;
  temperatureValue[16]=-12;
  temperatureValue[17]=-11.5;
  temperatureValue[18]=-11;
  temperatureValue[19]=-10.5;
  temperatureValue[20]=-10;
  temperatureValue[21]=-9.5;
  temperatureValue[22]=-9;
  temperatureValue[23]=-8.5;
  temperatureValue[24]=-8;
  temperatureValue[25]=-7.5;
  temperatureValue[26]=-7;
  temperatureValue[27]=-6.5;
  temperatureValue[28]=-6;
  temperatureValue[29]=-5.5;
  temperatureValue[30]=-5;
  temperatureValue[31]=-4.5;
  temperatureValue[32]=-4;
  temperatureValue[33]=-3.5;
  temperatureValue[34]=-3;
  temperatureValue[35]=-2.5;
  temperatureValue[36]=-2;
  temperatureValue[37]=-1.5;
  temperatureValue[38]=-1;
  temperatureValue[39]=-0.5;
  temperatureValue[40]=0;
  temperatureValue[41]=0.5;
  temperatureValue[42]=1;
  temperatureValue[43]=1.5;
  temperatureValue[44]=2;
  temperatureValue[45]=2.5;
  temperatureValue[46]=3;
  temperatureValue[47]=3.5;
  temperatureValue[48]=4;
  temperatureValue[49]=4.5;
  temperatureValue[50]=5;
  temperatureValue[51]=5.5;
  temperatureValue[52]=6;
  temperatureValue[53]=6.5;
  temperatureValue[54]=7;
  temperatureValue[55]=7.5;
  temperatureValue[56]=8;
  temperatureValue[57]=8.5;
  temperatureValue[58]=9;
  temperatureValue[59]=9.5;
  temperatureValue[60]=10;
  temperatureValue[61]=10.5;
  temperatureValue[62]=11;
  temperatureValue[63]=11.5;
  temperatureValue[64]=12;
  temperatureValue[65]=12.5;
  temperatureValue[66]=13;
  temperatureValue[67]=13.5;
  temperatureValue[68]=14;
  temperatureValue[69]=14.5;
  temperatureValue[70]=15;
  temperatureValue[71]=15.5;
  temperatureValue[72]=16;
  temperatureValue[73]=16.5;
  temperatureValue[74]=17;
  temperatureValue[75]=17.5;
  temperatureValue[76]=18;
  temperatureValue[77]=18.5;
  temperatureValue[78]=19;
  temperatureValue[79]=19.5;
  temperatureValue[80]=20;
  temperatureValue[81]=20.5;
  temperatureValue[82]=21;
  temperatureValue[83]=21.5;
  temperatureValue[84]=22;
  temperatureValue[85]=22.5;
  temperatureValue[86]=23;
  temperatureValue[87]=23.5;
  temperatureValue[88]=24;
  temperatureValue[89]=24.5;
  temperatureValue[90]=25;
  temperatureValue[91]=25.5;
  temperatureValue[92]=26;
  temperatureValue[93]=26.5;
  temperatureValue[94]=27;
  temperatureValue[95]=27.5;
  temperatureValue[96]=28;
  temperatureValue[97]=28.5;
  temperatureValue[98]=29;
  temperatureValue[99]=29.5;
  temperatureValue[100]=30;
  temperatureValue[101]=30.5;
  temperatureValue[102]=31;
  temperatureValue[103]=31.5;
  temperatureValue[104]=32;
  temperatureValue[105]=32.5;
  temperatureValue[106]=33;
  temperatureValue[107]=33.5;
  temperatureValue[108]=34;
  temperatureValue[109]=34.5;
  temperatureValue[110]=35;
  temperatureValue[111]=35.5;
  temperatureValue[112]=36;
  temperatureValue[113]=36.5;
  temperatureValue[114]=37;
  temperatureValue[115]=37.5;
  temperatureValue[116]=38;
  temperatureValue[117]=38.5;
  temperatureValue[118]=39;
  temperatureValue[119]=39.5;
  temperatureValue[120]=40;
  temperatureValue[121]=40.5;
  temperatureValue[122]=41;
  temperatureValue[123]=41.5;
  temperatureValue[124]=42;
  temperatureValue[125]=42.5;
  temperatureValue[126]=43;
  temperatureValue[127]=43.5;
  temperatureValue[128]=44;
  temperatureValue[129]=44.5;
  temperatureValue[130]=45;
  temperatureValue[131]=45.5;
  temperatureValue[132]=46;
  temperatureValue[133]=46.5;
  temperatureValue[134]=47;
  temperatureValue[135]=47.5;
  temperatureValue[136]=48;
  temperatureValue[137]=48.5;
  temperatureValue[138]=49;
  temperatureValue[139]=49.5;
  temperatureValue[140]=50;
  temperatureValue[141]=50.5;
  temperatureValue[142]=51;
  temperatureValue[143]=51.5;
  temperatureValue[144]=52;
  temperatureValue[145]=52.5;
  temperatureValue[146]=53;
  temperatureValue[147]=53.5;
  temperatureValue[148]=54;
  temperatureValue[149]=54.5;
  temperatureValue[150]=55;
  temperatureValue[151]=55.5;
  temperatureValue[152]=56;
  temperatureValue[153]=56.5;
  temperatureValue[154]=57;
  temperatureValue[155]=57.5;
  temperatureValue[156]=58;
  temperatureValue[157]=58.5;
  temperatureValue[158]=59;
  temperatureValue[159]=59.5;
  temperatureValue[160]=60;
  temperatureValue[161]=60.5;
  temperatureValue[162]=61;
  temperatureValue[163]=61.5;
  temperatureValue[164]=62;
  temperatureValue[165]=62.5;
  temperatureValue[166]=63;
  temperatureValue[167]=63.5;
  temperatureValue[168]=64;
  temperatureValue[169]=64.5;
  temperatureValue[170]=65;
  temperatureValue[171]=65.5;
  temperatureValue[172]=66;
  temperatureValue[173]=66.5;
  temperatureValue[174]=67;
  temperatureValue[175]=67.5;
  temperatureValue[176]=68;
  temperatureValue[177]=68.5;
  temperatureValue[178]=69;
  temperatureValue[179]=69.5;
  temperatureValue[180]=70;
  temperatureValue[181]=70.5;
  temperatureValue[182]=71;
  temperatureValue[183]=71.5;
  temperatureValue[184]=72;
  temperatureValue[185]=72.5;
  temperatureValue[186]=73;
  temperatureValue[187]=73.5;
  temperatureValue[188]=74;
  temperatureValue[189]=74.5;
  temperatureValue[190]=75;
  temperatureValue[191]=75.5;
  temperatureValue[192]=76;
  temperatureValue[193]=76.5;
  temperatureValue[194]=77;
  temperatureValue[195]=77.5;
  temperatureValue[196]=78;
  temperatureValue[197]=78.5;
  temperatureValue[198]=79;
  temperatureValue[199]=79.5;
  temperatureValue[200]=80;
  temperatureValue[201]=80.5;
  temperatureValue[202]=81;
  temperatureValue[203]=81.5;
  temperatureValue[204]=82;
  temperatureValue[205]=82.5;
  temperatureValue[206]=83;
  temperatureValue[207]=83.5;
  temperatureValue[208]=84;
  temperatureValue[209]=84.5;
  temperatureValue[210]=85;
  temperatureValue[211]=85.5;
  temperatureValue[212]=86;
  temperatureValue[213]=86.5;
  temperatureValue[214]=87;
  temperatureValue[215]=87.5;
  temperatureValue[216]=88;
  temperatureValue[217]=88.5;
  temperatureValue[218]=89;
  temperatureValue[219]=89.5;
  temperatureValue[220]=90;
  temperatureValue[221]=90.5;
  temperatureValue[222]=91;
  temperatureValue[223]=91.5;
  temperatureValue[224]=92;
  temperatureValue[225]=92.5;
  temperatureValue[226]=93;
  temperatureValue[227]=93.5;
  temperatureValue[228]=94;
  temperatureValue[229]=94.5;
  temperatureValue[230]=95;
  temperatureValue[231]=95.5;
  temperatureValue[232]=96;
  temperatureValue[233]=96.5;
  temperatureValue[234]=97;
  temperatureValue[235]=97.5;
  temperatureValue[236]=98;
  temperatureValue[237]=98.5;
  temperatureValue[238]=99;
  temperatureValue[239]=99.5;
  temperatureValue[240]=100;
  temperatureValue[241]=1000;
  rValue[0]=95337;
  rValue[1]=92655.9;
  rValue[2]=90058;
  rValue[3]=87540.6;
  rValue[4]=85100.9;
  rValue[5]=82736.4;
  rValue[6]=80444.5;
  rValue[7]=78222.7;
  rValue[8]=76068.9;
  rValue[9]=73980.6;
  rValue[10]=71955.8;
  rValue[11]=69992.3;
  rValue[12]=68088.1;
  rValue[13]=66241.2;
  rValue[14]=64449.9;
  rValue[15]=62712.2;
  rValue[16]=61026.4;
  rValue[17]=59390.8;
  rValue[18]=57803.8;
  rValue[19]=56263.9;
  rValue[20]=54769.4;
  rValue[21]=53318.9;
  rValue[22]=51911.1;
  rValue[23]=50544.5;
  rValue[24]=49217.8;
  rValue[25]=47929.8;
  rValue[26]=46679.2;
  rValue[27]=45464.9;
  rValue[28]=44285.6;
  rValue[29]=43140.3;
  rValue[30]=42027.9;
  rValue[31]=40947.4;
  rValue[32]=39897.8;
  rValue[33]=38878;
  rValue[34]=37887.3;
  rValue[35]=36924.6;
  rValue[36]=35989.2;
  rValue[37]=35080.1;
  rValue[38]=34196.5;
  rValue[39]=33337.8;
  rValue[40]=32503;
  rValue[41]=31691.5;
  rValue[42]=30902.6;
  rValue[43]=30135.5;
  rValue[44]=29389.6;
  rValue[45]=28664.4;
  rValue[46]=27959;
  rValue[47]=27273;
  rValue[48]=26605.8;
  rValue[49]=25956.7;
  rValue[50]=25325.4;
  rValue[51]=24711.1;
  rValue[52]=24113.5;
  rValue[53]=23532;
  rValue[54]=22966.1;
  rValue[55]=22415.4;
  rValue[56]=21879.5;
  rValue[57]=21357.9;
  rValue[58]=20850.2;
  rValue[59]=20355.9;
  rValue[60]=19874.7;
  rValue[61]=19406.3;
  rValue[62]=18950.2;
  rValue[63]=18506;
  rValue[64]=18073.5;
  rValue[65]=17652.3;
  rValue[66]=17242.1;
  rValue[67]=16842.6;
  rValue[68]=16453.4;
  rValue[69]=16074.3;
  rValue[70]=15704.9;
  rValue[71]=15345;
  rValue[72]=14994.4;
  rValue[73]=14652.8;
  rValue[74]=14319.8;
  rValue[75]=13995.4;
  rValue[76]=13679.2;
  rValue[77]=13371;
  rValue[78]=13070.5;
  rValue[79]=12777.7;
  rValue[80]=12492.2;
  rValue[81]=12213.8;
  rValue[82]=11942.5;
  rValue[83]=11677.8;
  rValue[84]=11419.8;
  rValue[85]=11168.1;
  rValue[86]=10922.7;
  rValue[87]=10683.4;
  rValue[88]=10449.9;
  rValue[89]=10222.2;
  rValue[90]=10000;
  rValue[91]=9783.3;
  rValue[92]=9571.8;
  rValue[93]=9365.5;
  rValue[94]=9164.2;
  rValue[95]=8967.7;
  rValue[96]=8776;
  rValue[97]=8588.9;
  rValue[98]=8406.3;
  rValue[99]=8228.1;
  rValue[100]=8054.1;
  rValue[101]=7884.2;
  rValue[102]=7718.4;
  rValue[103]=7556.5;
  rValue[104]=7398.5;
  rValue[105]=7244.2;
  rValue[106]=7093.5;
  rValue[107]=6946.3;
  rValue[108]=6802.6;
  rValue[109]=6662.2;
  rValue[110]=6525.1;
  rValue[111]=6391.2;
  rValue[112]=6260.4;
  rValue[113]=6132.6;
  rValue[114]=6007.7;
  rValue[115]=5885.8;
  rValue[116]=5766.6;
  rValue[117]=5650.1;
  rValue[118]=5536.3;
  rValue[119]=5425.1;
  rValue[120]=5316.4;
  rValue[121]=5210.2;
  rValue[122]=5106.4;
  rValue[123]=5004.9;
  rValue[124]=4905.7;
  rValue[125]=4808.8;
  rValue[126]=4714;
  rValue[127]=4621.3;
  rValue[128]=4530.7;
  rValue[129]=4442.1;
  rValue[130]=4355.4;
  rValue[131]=4270.7;
  rValue[132]=4187.8;
  rValue[133]=4106.8;
  rValue[134]=4027.5;
  rValue[135]=3950;
  rValue[136]=3874.2;
  rValue[137]=3800;
  rValue[138]=3727.5;
  rValue[139]=3656.5;
  rValue[140]=3587;
  rValue[141]=3519;
  rValue[142]=3452.5;
  rValue[143]=3387.5;
  rValue[144]=3323.8;
  rValue[145]=3261.5;
  rValue[146]=3200.5;
  rValue[147]=3140.8;
  rValue[148]=3082.4;
  rValue[149]=3025.2;
  rValue[150]=2969.2;
  rValue[151]=2914.4;
  rValue[152]=2860.8;
  rValue[153]=2808.2;
  rValue[154]=2756.8;
  rValue[155]=2706.5;
  rValue[156]=2657.2;
  rValue[157]=2608.9;
  rValue[158]=2561.6;
  rValue[159]=2515.3;
  rValue[160]=2470;
  rValue[161]=2425.5;
  rValue[162]=2382;
  rValue[163]=2339.4;
  rValue[164]=2297.7;
  rValue[165]=2256.8;
  rValue[166]=2216.7;
  rValue[167]=2177.5;
  rValue[168]=2139;
  rValue[169]=2101.3;
  rValue[170]=2064.4;
  rValue[171]=2028.2;
  rValue[172]=1992.8;
  rValue[173]=1958;
  rValue[174]=1924;
  rValue[175]=1890.6;
  rValue[176]=1857.9;
  rValue[177]=1825.8;
  rValue[178]=1794.4;
  rValue[179]=1763.6;
  rValue[180]=1733.4;
  rValue[181]=1703.7;
  rValue[182]=1674.7;
  rValue[183]=1646.2;
  rValue[184]=1618.3;
  rValue[185]=1591;
  rValue[186]=1564.1;
  rValue[187]=1537.8;
  rValue[188]=1512;
  rValue[189]=1486.7;
  rValue[190]=1461.9;
  rValue[191]=1437.5;
  rValue[192]=1413.6;
  rValue[193]=1390.2;
  rValue[194]=1367.2;
  rValue[195]=1344.7;
  rValue[196]=1322.5;
  rValue[197]=1300.8;
  rValue[198]=1279.5;
  rValue[199]=1258.6;
  rValue[200]=1238.1;
  rValue[201]=1218;
  rValue[202]=1198.3;
  rValue[203]=1178.9;
  rValue[204]=1159.9;
  rValue[205]=1141.2;
  rValue[206]=1122.9;
  rValue[207]=1105;
  rValue[208]=1087.3;
  rValue[209]=1070;
  rValue[210]=1053;
  rValue[211]=1036.3;
  rValue[212]=1019.9;
  rValue[213]=1003.8;
  rValue[214]=988;
  rValue[215]=972.5;
  rValue[216]=957.3;
  rValue[217]=942.4;
  rValue[218]=927.7;
  rValue[219]=913.3;
  rValue[220]=899.1;
  rValue[221]=885.2;
  rValue[222]=871.5;
  rValue[223]=858.1;
  rValue[224]=845;
  rValue[225]=832;
  rValue[226]=819.3;
  rValue[227]=806.8;
  rValue[228]=794.5;
  rValue[229]=782.5;
  rValue[230]=770.7;
  rValue[231]=759;
  rValue[232]=747.6;
  rValue[233]=736.4;
  rValue[234]=725.3;
  rValue[235]=714.5;
  rValue[236]=703.8;
  rValue[237]=693.3;
  rValue[238]=683.1;
  rValue[239]=672.9;
  rValue[240]=663;
  rValue[241]=0;
}


double getTemperature(double vData) {
  double vValue = vData / (double)1024;
  double calculatedRValue = vValue * (double)Rs / ((double)Vcc - vValue);
  Serial.println(calculatedRValue);
  Serial.println(sizeof(rValue));
  for(int i = 241; i >= 0; i--) {
    double lowerR = rValue[i];
    double higherR = rValue[i - 1];
    // Serial.print(i);
    // Serial.print(":low:");
    // Serial.print(lowerR);
    // Serial.print("high:");
    // Serial.println(higherR);
    if (calculatedRValue >= lowerR && calculatedRValue < higherR) {
      return temperatureValue[i];
    }
  }
  return -1;
}